[project]
name = 'Blockchain-Based-Legal-Contract-Lifecycle-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.amendment-tracking]
path = 'contracts/amendment-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.legal-entity-verification]
path = 'contracts/legal-entity-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
